[package]
name = "rr-tools"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "rr-tools"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
hound = "3.5"
ron = "0.12"
rr-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
